# Application-managed secrets for CloudPet.
#
# Only the JWT signing key lives here. It is generated by Terraform and stored
# as an SSM Parameter Store SecureString encrypted with the default
# alias/aws/ssm managed key. The generated value is present in Terraform state
# -- an explicitly accepted tradeoff for this project (D2).
#
# DATABASE_URL is deliberately NOT stored: the RDS password rotates, so the
# connection string is assembled at application boot from the live RDS-managed
# secret. That runtime behaviour belongs to a later milestone.

resource "random_password" "jwt_secret_key" {
  length = 64

  # Comfortably exceeds the application's 32-character minimum and keeps to a
  # shell/env-safe character set (letters, digits, and "-_.~").
  special          = true
  override_special = "-_.~"
  min_upper        = 8
  min_lower        = 8
  min_numeric      = 8
  min_special      = 4
}

resource "aws_ssm_parameter" "jwt_secret_key" {
  name  = var.parameter_name
  type  = "SecureString"
  value = random_password.jwt_secret_key.result
  tier  = "Standard"
  # key_id omitted on purpose: AWS uses the default alias/aws/ssm managed key.

  tags = merge(var.tags, { Name = var.parameter_name })
}
